name: ${project.name}
version: ${project.version}
main: ${main.class}
api-version: 1.13
author: ${author}

softdepend:
  - GadgetsMenu
  - AlonsoLevels
  - AlonsoLeagues

commands:

libraries:
  - org.openjdk.nashorn:nashorn-core:15.3